### ISSUE TITLE
sqlite3_exec() returns 1 not 0

### ISSUE THREAD

**Issue by mpadge** [mpadge/bikedata#12]
@richardellison a plea for help here: travis currently [fails](https://travis-ci.org/mpadge/bikedata/builds/220877138) because the `sqlite3_exec()` statement at the end of [`rcpp_import_stn_df`](https://github.com/mpadge/bikedata/blob/master/src/read-station-files.h#L413) returns 1 on travis, yet i get 0. I can reproduce the travis failure in a trusty container, but not in xenial, so this must have something to do with `sqlite3` versions? Any insight from your side very much appreciated!

These lines suffice to reproduce (in this case, for Chicago test data, but same result arises for London):
```
devtools::load_all (".", export_all=TRUE)
bikedb <- "junkdb"
data_dir <- "./tests"
rcpp_create_sqlite3_db (bikedb)
flists <- bike_unzip_files_chicago (data_dir, bikedb)
ch_stns <- bike_get_chicago_stations (flists)
head (ch_stns)
nstations <- rcpp_import_stn_df (bikedb, ch_stns, 'ch')
```
The query structure is absolutely okay and works fine on >= 16.04, so this really does just seem to be an internal SQLite3 thing, but one for which we really need to find a solution. Set up of `stations` table is [here](https://github.com/mpadge/bikedata/blob/master/src/sqlite3db-setup.cpp#L68-L76) - could it be an issue with the `UNIQUE` statement? All other otherwise entirely equivalent `sqlite3_exec()` statements return 0 as expected, so that's the only real different that jumps out to me.

Oh, and going the full `_prepare_v2() -> _step() -> _reset()` path also returns identical results (trusty = fail, xenial = pass).

**Comment by richardellison** [comment]
I'll have a look. Just by looking at the code the query looks OK to me. I suspected that INSERT OR IGNORE was not supported in the earlier version but it seems to have been supported since at least 2008 so that doesn't appear to be the issue.

**Comment by mpadge** [comment]
Thanks Richard - note that i've now removed the offending data so get travis to pass, but you can still get them from [this commit](https://github.com/mpadge/bikedata/tree/9904d8b7323d8e06208091816bdb694ad3e32609/tests) - `sample-divvy...` (chicago) will do the trick.

**Comment by mpadge** [comment]
@richardellison in case you've got time for this, i've parked a minimal reproducible example in [this repo](https://github.com/mpadge/sqlite3-test) - simply clone and play around. Passes on xenial; fails on trusty / travis. I hope to be able to use that to dig down to the root of the problem. Other than this issue and some spit and polish, the package is pretty much done.

**Comment by mpadge** [comment]
It's okay Richard, I've found the issue. Simple data cleaning problem with the stations files - still not sure why that would cause it to fail on some systems yet pass on others, but i'll have it all resolved soon.

**Comment by richardellison** [comment]
Well done! Out of interest, what was the data cleaning problem? A stray backtick or something similar? Not sure why it would work on some but not others unless there was an issue with the character set being used on Travis.

**Comment by mpadge** [comment]
I intend to delve a bit further next week, but it has to be a difference in the way different versions of SQLite3 handle either missing or malformed values

**Comment by mpadge** [comment]
@richardellison ignore my comments of last week: it's actually because the version of `sqlite3` on `travis/trusty`, which is 3.8.2, only allows query strings to contain 500 elements, whereas later versions do not have this restriction. Solution just required breaking up the query into smaller chunks. Now we can both put that knowledge in the back of our noggins somewhere and get on with something more useful ...
