### ISSUE TITLE
appveyor

### ISSUE THREAD

**Issue by mpadge** [mpadge/bikedata#22]
@richardellison Hopefully a final question for you, and this one just in case you've got any insight: Do you have any idea how to get appveyor working with `sqlite3`? I'm currently loading it through [pre-installing `RSQLite`](https://github.com/mpadge/bikedata/blob/master/appveyor.yml#L21), but this fails because the `sqlite3.h` file can't be found. Note that it currently also fails on [`devtools`](https://github.com/hadley/devtools), presumably for the same reason, so it seems like a solution ain't easy.

Would you perchance happen to have any idea how to help here?

(The good news is that the package is otherwise done and dusted and will be submitted this week - first a CRAN upload, then ropensci.)

**Comment by mpadge** [comment]
Note that `RSQLite` should install `sqlite`, and also [this commit](https://github.com/mpadge/bikedata/commit/e4fd24297f5f41b6e59958f4d6ce1218d2f779db) installs it explicitly with [`chocolatey`](https://www.appveyor.com/docs/build-configuration/#chocolatey) which should work, yet still doesn't. The `lsqlite3` library is passed to `Makevars` by the [`config` file](https://github.com/mpadge/bikedata/blob/master/configure), so that's also not the problem.

**Comment by richardellison** [comment]
If I remember correctly, RSQLite bundles a copy of SQLite in the package, so never uses the common header files. It looks to me like the sqlite includes directory is not being passed correctly for some reason as it is complaining about sqlite3.h (which the lsqlite3 call would not have any effect on).

**Comment by richardellison** [comment]
Do you know where chocolatey installs sqlite3 to and if it includes the header files?

**Comment by richardellison** [comment]
It it doesn't include the header files we may need to revert to something like [this](https://github.com/jgallagher/rusqlite/issues/235#issuecomment-279428035).

**Comment by mpadge** [comment]
Thanks @richardellison for the quick response! Alas, I still can't get it work. No matter what I try, it always fails on `sqlite.h: No such file or directory`. That even applies when the header (`almagamation`) files are [extracted in to a directory that is definitely on the `$PATH`](https://github.com/mpadge/bikedata/commit/6126542f27324d3fee66fa02612cc66096c76d06). I give up (for the moment at least)! 

(One note fyi: The `dll` can't be downloaded for an `R` package, because it is then incorporated into the package itself, which consequently fails `R CMD check`, but the `chocolatey` install does the job there, so that's okay.)

**Comment by mpadge** [comment]
and wouldn't ya know it, it's actually a pervasive windows problem: The package fails on `win-builder.r-project` as well, with undefined references to all `sqlite3.h` bindings. :-1: Gotta figure this out after all ...

**Comment by richardellison** [comment]
Is it possible to download the necessary files when compiling on Windows only? Wouldn't solve the problem of the Windows binaries being large though.

On the other hand, is 7MB really going to be an issue when the package is intended to download datasets many times larger than this?

**Comment by mpadge** [comment]
It's really just an appveyor issue - the `win-builder` machines have no probs finding the headers, and I'd be highly resistant to such a package inflation for reasons that have nothing to do with cran. I'll remain hopeful of a more lightweight solution for a bit longer...

**Comment by mpadge** [comment]
@richardellison Finally back onto this with what appears to be the only viable solution of just bundling the whole damn lot. Whatever works in the end ... Thanks for your input on this issue. closing now.
