### ISSUE TITLE
Test failures with development version of dplyr

### ISSUE THREAD

**Issue by krlmlr** [mpadge/bikedata#40]
Some tests that use `expect_silent()` fail, probably since https://github.com/tidyverse/dplyr/pull/2878.

Related: https://github.com/tidyverse/dbplyr/pull/18.

**Comment by mpadge** [comment]
Thanks for that Kirill - will defnitely fix!

**Comment by mpadge** [comment]
@krlmlr It was easy for me to simply remove the `dplyr` dependency in favour of direct `RSQLite` functions, but one Q remains: Why is the warning discussed in [`tidyverse/dbplyr/pull/18`](https://github.com/tidyverse/dbplyr/pull/18) not issued in code like this:
```
fn1 <- function (db_name){
  db <- RSQLite::dbConnect (RSQLite::SQLite(), db_name, create = FALSE)
  res <- dplyr::collect (dplyr::tbl (db, 'a_table')) # or whatever
  RSQLite::dbDisconnect (db)
}
```
yet this code flags the warning:
```
fn1 <- function (db_name){
  db <- RSQLite::dbConnect (RSQLite::SQLite(), db_name, create = FALSE)
  res <- fn2 (db)
  RSQLite::dbDisconnect (db)
}
fn2 <- function (db_con){
  res <- dplyr::collect (dplyr::tbl (db_con, 'a_table')) # or whatever
}
```

**Comment by krlmlr** [comment]
The warning would be issued during garbage collection, you can make them more predictable by inserting `gc()` calls (but they should be removed in production code).
