### ISSUE TITLE
strtokm function

### ISSUE THREAD

**Issue by mpadge** [mpadge/bikedata#6]
@richardellison dumping issues on you here. The `strtokm` function is great, but actually not really necessary anymore, because the NYC data files were only double quoted up until 201412, and quotes disappeared from 201501 onwards. At present, I just pass a `delim` option to [`read_one_line`](https://github.com/mpadge/bikedata/blob/master/src/spatialitedb.cpp#L99-L106) which is either `","` or just `,`. Obviously we could - and should, hence this issue - just `boost::replace_all (line, "\"", "")` at the outset. This would then enable reversion to direct `strtok` rather than the multi-char `strtokm`, but `strok` behaves slightly differently, and prevents the [last token](https://github.com/mpadge/bikedata/blob/master/src/spatialitedb.cpp#L146) from being extracted in the neat way it currently is.

I implemented an ugly work-around by sticking an extra delim on the end of the line, but didn't commit that because there must be a better way. I'd really appreciate it if you could give it a try with `std::strok` instead of `strokm` and see if you can find a neat solution.

**Comment by richardellison** [comment]
Using ```boost::replace_all(line, "\"", "")``` should allow a reversion to strtok. Since we can pass multiple (single) delimiters to strtok, it should work for the last token as well.

I'll have a go and see how I get on.

**Comment by richardellison** [comment]
I remember now why I initially didn't just use strtok. It was because I wasn't sure if any of the data would contain strings with commas (in an address for instance). The Citibike data doesn't seem to have this issue but it is something to keep in mind for other systems.

**Comment by richardellison** [comment]
One alternative if we want to use strtok together with boost::replace_all would be to use ```boost::replace_all(line, "\",\"", "?")``` where instead of the question mark we use an infrequently used character.

**Comment by mpadge** [comment]
nah, we've still got comma separators, so can't stick anything but black spaces in (with `strok`). The good news is that **all** data thus far from global bike systems is ultimately stored in strict `.csv` format, so comma's are used exclusively as field delimiters and never as punctuation. That means we can definitely rely on comma separators at all times.

i didn't document my previous attempts, but recall that everything worked fine simply removing double quotes up until the line ending, but I couldn't get `strok` to properly return the final token. The `rm_dos_end` function was intended to solve it, but still didn't somehow.

**Comment by richardellison** [comment]
In that case I'll go ahead and try removing any speech marks and use strtok.

**Comment by mpadge** [comment]
Closing this because `strtokm` is utlimately still needed because there are cities (such as London) in which station names do have commas, yet are delimited by double quotes. All such cases use `strtokm`, while all others revert to `std::strtok` where possible.
